apiVersion: v2
name: openrouter-bot
description: OpenRouter in Telegram 
version: 0.2.0
appVersion: "0.5.0"

icon: https://raw.githubusercontent.com/shevchukma/openrouter-bot/main/img/logo.png

home: https://github.com/shevchukma/openrouter-bot

sources:
  - https://github.com/shevchukma/openrouter-bot

maintainers:
  - name: shevchukma
    url: https://github.com/shevchukma

keywords:
  - telegram
  - bot
  - openrouter
  - ai
  - llm
  - gpt