services:
  OpenRouter-Bot:
    container_name: OpenRouter-Bot
    image: velikoross/openrouter-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env:/openrouter-bot/.env
    restart: unless-stopped